module.exports = {
  MONGOURI: process.env.MONGODBPRODUCTION,
  STRIPESECRETKEY: process.env.STRIPESECRETKEY,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_SECRET_API: process.env.CLOUDINARY_SECRET_API,
};
